project_id = "suynbvqdtzuwxqrrgrgn"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.convert-to-pdf]
verify_jwt = false